apiVersion: v1
kind: Service
metadata:
  name: ds-idrepo-nodeport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: ds-idrepo
    app.kubernetes.io/name: ds
  ports:
    - protocol: TCP
      port: 1389
      targetPort: 1389
      nodePort: 31389
