kind: Component
apiVersion: kustomize.config.k8s.io/v1alpha1
commonLabels:
  app.kubernetes.io/part-of: forgerock
images:
- digest: sha256:39ee16baf3a89fd6deded3c3501f9d865810dda4a36b94b7e039a02abb6bb6c2
  name: am
  newName: 673492047887.dkr.ecr.us-east-1.amazonaws.com/bwolfefrcdk/am:dda3f47-dirty
- digest: sha256:fb05e253d456d11397304165d9301065d170c96368c959b6432966b76c77e1fb
  name: amster
  newName: 673492047887.dkr.ecr.us-east-1.amazonaws.com/bwolfefrcdk/amster:614bcca-dirty
- digest: sha256:248408b4a2aa4488f306d7da8fe38d452fb7b11ac8851fa130307069a2c8ac19
  name: ds
  newName: 673492047887.dkr.ecr.us-east-1.amazonaws.com/bwolfefrcdk/ds:dfa7d67
- name: ds-cts
  newName: us-docker.pkg.dev/forgeops-public/images/ds-cts
  newTag: 7.2.0
- name: ds-idrepo
  newName: us-docker.pkg.dev/forgeops-public/images/ds-idrepo
  newTag: 7.2.0
- name: git-server
  newName: us-docker.pkg.dev/forgeops-public/images/git-server
- digest: sha256:9006406e40a53e923a28dacc7b62018a93dc520086b8e78c9afa39e9a80b6da7
  name: idm
  newName: 673492047887.dkr.ecr.us-east-1.amazonaws.com/bwolfefrcdk/idm:0d1deda-dirty
- digest: sha256:9b6f0154732c6349997c5d071f443d97c6d9b1a916162ec84fe781d3f9c83534
  name: ig
  newName: 673492047887.dkr.ecr.us-east-1.amazonaws.com/bwolfefrcdk/ig:cb6e4e0-dirty
